######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 14 23:07:59 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
